USE QhatuPERU
go

SELECT TIENDA.CodTienda, TIENDA.Distrito,
	SUM(GUIA_DETALLE.CantidadEnviada * GUIA_DETALLE.PrecioVenta)
	AS MontoTotal
FROM TIENDA INNER JOIN GUIA_ENVIO
	ON TIENDA.CodTienda = GUIA_ENVIO.CodTienda
INNER JOIN GUIA_DETALLE
	ON GUIA_ENVIO.NumGuia = GUIA_DETALLE.NumGuia
GROUP BY TIENDA.CodTienda, TIENDA.Distrito
go