USE QhatuPERU
go

WITH ComprasCTE(Orden, Fecha, Proveedor, Monto)
AS
(
SELECT ORDEN_COMPRA.NumOrden,
	CONVERT(CHAR(10), ORDEN_COMPRA.FechaOrden, 102),
	PROVEEDOR.NomProveedor,
	SUM(ORDEN_DETALLE.CantidadRecibida *
		ORDEN_DETALLE.PrecioCompra)
FROM ORDEN_COMPRA INNER JOIN ORDEN_DETALLE
	ON ORDEN_COMPRA.NumOrden = ORDEN_DETALLE.NumOrden
INNER JOIN ARTICULO
	ON ORDEN_DETALLE.CodArticulo = ARTICULO.CodArticulo
INNER JOIN PROVEEDOR
	ON ARTICULO.CodProveedor = PROVEEDOR.CodProveedor
GROUP BY ORDEN_COMPRA.NumOrden,
	CONVERT(CHAR(10), ORDEN_COMPRA.FechaOrden, 102),
	PROVEEDOR.NomProveedor
)
SELECT * FROM ComprasCTE
	WHERE Fecha = '2013.04.11'
go