USE QhatuPERU
go

SELECT YEAR(GUIA_ENVIO.FechaSalida) AS Año,
	MONTH(GUIA_ENVIO.FechaSalida) AS Mes,
	SUM(GUIA_DETALLE.CantidadEnviada) AS UnidadesEnviadas
FROM GUIA_ENVIO INNER JOIN GUIA_DETALLE
	ON GUIA_ENVIO.NumGuia = GUIA_DETALLE.NumGuia
WHERE GUIA_DETALLE.CodArticulo = 37
GROUP BY YEAR(GUIA_ENVIO.FechaSalida),
	MONTH(GUIA_ENVIO.FechaSalida)
go