USE QhatuPERU
go

CREATE TABLE LINEA (
	CodLinea	  int IDENTITY(1,1) PRIMARY KEY,
	NomLinea	  varchar(20) NOT NULL,
	Descripcion varchar(40) NULL )
go

INSERT LINEA
	VALUES('GOLOSINAS', 'GALLETAS,CHOCOLATES,CARAMELOS,TOFFES')
INSERT LINEA
	VALUES('EMBUTIDOS', 'JAMONADAS,JAMONES,SALCHICHAS,CHORIZOS')
INSERT LINEA
	VALUES('HIGIENE PERSONAL', 'JABONES,P.DENTALES,SHAMPOOS,P.H.')
go

SELECT * FROM LINEA
go



