USE QhatuPERU
go

SELECT ARTICULO.CodArticulo,
	ARTICULO.DescripcionArticulo,
	GUIA_DETALLE.CantidadEnviada
FROM ARTICULO INNER JOIN GUIA_DETALLE
	ON ARTICULO.CodArticulo = GUIA_DETALLE.CodArticulo
ORDER BY ARTICULO.CodArticulo
go

SELECT ARTICULO.CodArticulo,
	ARTICULO.DescripcionArticulo,
	GUIA_DETALLE.CantidadEnviada
FROM ARTICULO LEFT OUTER JOIN GUIA_DETALLE
	ON ARTICULO.CodArticulo = GUIA_DETALLE.CodArticulo
ORDER BY ARTICULO.CodArticulo
go

SELECT ARTICULO.CodArticulo,
	ARTICULO.DescripcionArticulo,
	GUIA_DETALLE.CantidadEnviada
FROM ARTICULO LEFT OUTER JOIN GUIA_DETALLE
	ON ARTICULO.CodArticulo = GUIA_DETALLE.CodArticulo
WHERE GUIA_DETALLE.CantidadEnviada IS NULL
ORDER BY ARTICULO.CodArticulo
go

SELECT ARTICULO.CodArticulo,
	ARTICULO.DescripcionArticulo
FROM ARTICULO LEFT OUTER JOIN GUIA_DETALLE
	ON ARTICULO.CodArticulo = GUIA_DETALLE.CodArticulo
WHERE GUIA_DETALLE.CantidadEnviada IS NULL
ORDER BY ARTICULO.CodArticulo
go

