USE QhatuPERU
go

SELECT GUIA_ENVIO.NumGuia, GUIA_ENVIO.FechaSalida,
	GUIA_ENVIO.CodTienda, GUIA_DETALLE.CodArticulo,
	GUIA_DETALLE.PrecioVenta, GUIA_DETALLE.CantidadEnviada
FROM GUIA_ENVIO INNER JOIN GUIA_DETALLE
	ON GUIA_ENVIO.NumGuia = GUIA_DETALLE.NumGuia
WHERE GUIA_ENVIO.NumGuia = 27
go