USE QhatuPERU
go

SELECT MAX(FechaSalida) FROM GUIA_ENVIO
go

SELECT DISTINCT GUIA_DETALLE.CodArticulo,
	ARTICULO.DescripcionArticulo
FROM GUIA_DETALLE INNER JOIN ARTICULO
	ON GUIA_DETALLE.CodArticulo =
		ARTICULO.CodArticulo
INNER JOIN GUIA_ENVIO
	ON GUIA_DETALLE.NumGuia = GUIA_ENVIO.NumGuia
WHERE CONVERT(CHAR(10),
		GUIA_ENVIO.FechaSalida, 103) = 
		(SELECT CONVERT(CHAR(10), MAX(FechaSalida),
			103) FROM GUIA_ENVIO)
go


