USE QhatuPERU
go

SELECT GUIA_ENVIO.NumGuia,
	GUIA_ENVIO.FechaSalida,
	GUIA_ENVIO.CodTienda,
	SUM(GUIA_DETALLE.CantidadEnviada *
		GUIA_DETALLE.PrecioVenta) AS MontoTotal
FROM GUIA_ENVIO INNER JOIN GUIA_DETALLE
	ON GUIA_ENVIO.NumGuia = GUIA_DETALLE.NumGuia
GROUP BY GUIA_ENVIO.NumGuia,
	GUIA_ENVIO.FechaSalida,
	GUIA_ENVIO.CodTienda
HAVING GUIA_ENVIO.NumGuia = 27
go

	
