USE QhatuPERU
go

SELECT ARTICULO.CodArticulo,
	ARTICULO.DescripcionArticulo
FROM ARTICULO
WHERE EXISTS
	(SELECT * FROM GUIA_DETALLE
		WHERE ARTICULO.CodArticulo =
			GUIA_DETALLE.CodArticulo)
ORDER BY ARTICULO.CodArticulo
go
